### ISSUE TITLE
inconsistent behavior

### ISSUE THREAD

**Issue by michalmikolajczyk** [ionic-team/ionic-contrib-frosted-glass#2]
Hi, I managed to get this working... kind of :) and it's not working always, which is weird.

I use ion-nav-bar and the first thing is that the bar isn't grey, it stays white. Sometimes I get it to work, especially in a new browser session. When it does work, the bar's title is lost.

I also get this error, I think it might be related:
TypeError: Object [object global] has no method 'rAF'
    at http://127.0.0.1:9000/vendor/ionic.contrib.frostedGlass.js:64:16

I run ionic through connect, but when I just open local files, i get the same error.

I load ionic 0.9.25 through bower, angular is version 1.2.12

**Comment by mlynch** [comment]
Hey Michal,

That looks like an old version of the file. Try this one instead:
https://github.com/driftyco/ionic-contrib-frosted-glass/blob/master/ionic.contrib.frostedGlass.js

On Sun, Mar 2, 2014 at 3:43 PM, Michał Mikołajczyk <notifications@github.com

**Comment by michalmikolajczyk** [comment]
hi again, only now had the time to get back on it. Unfortunately, the error is the same. I keep getting no rAF method on window object.

So no blur for me atm. I did get it grey though, swapped the css to be loaded before main css.
Any idea on the rAF? :)

**Comment by vs4vijay** [comment]
@wiherek5 on which device you are trying? I am getting the same issue with Android. and content is sometimes broken.

**Comment by michalmikolajczyk** [comment]
I was checking it with Chrome on desktop.
